### ISSUE TITLE
Requisitos TP

### ISSUE THREAD

**Issue by mirabelli11** [DarioVega/CaC2023_Django_Grupo9#1]
- [x] ● El proyecto debe estar realizado en grupos de 5 o 6 personas según decisión del instructor, no pudiendo realizarse de manera individual.

- [x] ● El PIG debe subirse a un repositorio GIT público en la nube.
- [x] ● El proyecto deberá poseer al menos una aplicación de Django
- [x] ● Deben existir al menos 3 rutas distintas.
- [x] ● Debe existir al menos una vista parametrizada.
- [x] ● Se deben utilizar templates que cumplan con las siguientes características:

> - [x] • Debe haber al menos un template asociado a una vista.
> - [x] • Debe existir al menos una relación de herencia entre los templates.
> - [x] • Debe existir al menos un filtro aplicado.
> - [x] • Debe existir al menos un template que utilice archivos estáticos (js, css, etc).

- [ ] ● Se deben utilizar Django Forms que cumplan con las siguientes características:

> - [x] • Al menos un formulario debe poseer validaciones en el front-end y en el back-end
> - [x] • Debe haber al menos un formulario asociado a un template.
> - [x] • Debe haber al menos un formulario basado en clases.
> - [x] • Debe haber al menos un formulario asociado a un modelo.

- [x] ● Deben existir al menos dos modelos distintos.
- [x] ● En los modelos generados, debe haber al menos una relación de uno a muchos y una relación de muchos a muchos.
- [x] ● El proyecto debe funcionar utilizando un servidor de base de datos local dentro de los soportados (en el curso se recomienda PostgreSQL), y debe poseer las migraciones necesarias para su funcionamiento (no se permite utilizar SQLLite).
- [x] ● Debe poder accederse al admin de Django y al menos los modelos que poseen la relación muchos a muchos deben poder administrarse del mismo.
- [x] ● El proyecto debe poseer al menos una página a la que solo se pueda acceder mediante autenticación y la misma debe ser validada tanto en el front-end como el back-end.

**Comment by DarioVega** [comment]
Hemos alcanzado todos los objetivos pedidos.
